FROM python:3.10-slim

WORKDIR /app

COPY requirements.frontend.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY frontend/ frontend/

EXPOSE 8080

CMD ["python", "frontend/front.py"]
